name: cdxgen and Trivy from src

on:
  workflow_dispatch:
    inputs:
      src_dir:
        description: 'Source Folder'
        required: true
        default: ''
      src_type:
        description: 'Project Type (java, python, dotnet) see https://cyclonedx.github.io/cdxgen/#/PROJECT_TYPES'
        required: false
        default: 'java'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
     
      - name: Check
        run: |
          ls -la

      - name: Generate SBOM using trivy
        run: |
          docker run --rm \
            -v "$(pwd)":/app:rw \
            -v /tmp:/tmp \
            -t docker.io/aquasec/trivy:latest fs /${{ inputs.src_dir }} \
            --format "cyclonedx" \
            --scanners vuln,license \
            --output /tmp/trivy-report-cdxgen-src.json \
            /tmp/sbom.json

      - name: artifact name
        id: artifactname
        run: |
          out_name="${{ inputs.src_dir }}"
          out_name="${out_name//\//-}"  # Replace '/' with '-'
          echo "out_name=$out_name" >> $GITHUB_OUTPUT

      - name: Upload SBOM results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifactname.outputs.out_name }}
          path: /tmp/*.json
          if-no-files-found: warn
